version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo Build completed on 'date'
      - mvn package -Dmaven.test.skip
post_build:
  commands:
  - echo Build completed on 'date'
artifacts:
  files:

  - target/*.jar
discard-paths: yes

